name: Golang Setup
description: Install golang version and set cache of go module

inputs:
  repository:
    description: The owner and repository name
    required: true
  go-version:
    description: Version of golang that would like to install
    required: false
    default: '^1.17.2'

runs:
  using: composite
  steps:
    - name: Install go version ${{ inputs.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache module and tools
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin
          ./vendor
          /go/bin
        key: ${{ runner.os }}-go-cache-v1-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-cache-v1-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-go-cache-v1-${{ inputs.repository }}-
          ${{ runner.os }}-go-cache-v1-