name: Docker Build and Push
description: Build docker image and push to registry

inputs:
  repository:
    description: The owner and repository name
    required: false
    default: ${{ github.repository }}
  application_name:
    description: Name of application
    required: false
    default: ''
  token:
    description: ECR token
    required: true
  image:
    description: Docker image name
    required: false
  build_args:
    description: List of build-time variables
    required: false
  target:
    description: Indicate which build stage is the target build stage
    required: false
    default: ''
  dockerfile:
    description: Path to the dockerfile to be built.
    required: false
  gh_access_token:
    description: GitHub access token
    required: true

outputs:
  image_repo:
    description: Docker image repository
    value: ${{ steps.image.outputs.repo }}
  image_tag:
    description: Docker image's tag
    value: ${{ steps.image.outputs.tag }}

runs:
  using: composite
  steps:
    - uses: kkp-dfs/dime-github-actions-workflows/common@main
      with:
        gh_access_token: ${{ inputs.gh_access_token }}
    - shell: bash
      run: echo ${{ github.repository }}
    - name: Set docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.repository }}
        labels: |
          maintainer=${{ github.actor }}
          org.opencontainers.image.title=${{ inputs.application_name }}
          org.opencontainers.image.licenses=Copyright 2022 Dime Co., Ltd.
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=pr,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
          type=ref,event=pr,suffix=-latest
          type=ref,event=branch,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
          type=ref,event=branch,suffix=-{{sha}}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          type=raw,value={{sha}},enable=true
    - name: mask token
      shell: bash
      run: echo "::add-mask::${{ inputs.token }}"
    - name: Build & push docker images
      uses: kkp-dfs/dime-github-actions-workflows/kaniko@main
      with:
        image: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build_args: ${{ inputs.build_args }}
        token: ${{ inputs.token }}
        target: ${{ inputs.target }}
        dockerfile: ${{ inputs.dockerfile }}

    - id: image
      shell: bash
      run: |
        IMAGE=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[0]')
        echo "::set-output name=repo::$(echo $IMAGE | cut -d: -f1)"
        echo "::set-output name=tag::$(echo $IMAGE | cut -d: -f2)"
