name: Docker Build and Push
description: Build docker image and push to registry

inputs:
  repository:
    description: The owner and repository name
    required: true
  image:
    description: Docker image name
    required: false
  build_args:
    description: List of build-time variables
    required: false

outputs:
  docker_image:
    description: Docker image metadata
    value: ${{ steps.meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Get ECR details and copy .netrc file to context directory
      id: ecr
      shell: bash
      run: |
        REPOSITORY=$(aws ecr describe-repositories --region ap-southeast-1 --output text \
        --query 'repositories[].repositoryUri' --repository-name '${{ inputs.repository }}')
        TOKEN=$(aws ecr get-authorization-token --region ap-southeast-1 --output text \
        --query 'authorizationData[].authorizationToken')

        mkdir -p ~/.docker
        cat > ~/.docker/config.json <<EOF
        {"auths":{"915060398631.dkr.ecr.ap-southeast-1.amazonaws.com":{"auth":"$TOKEN"}}}
        EOF

        echo "::set-output name=repository::$REPOSITORY"
        cp ~/.netrc ./
    
    - name: Set docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.image || steps.ecr.outputs.repository }}
        tags: |
          type=ref,event=pr,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
          type=ref,event=pr,suffix=-latest
          type=ref,event=branch,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
          type=ref,event=branch
        labels: |
          org.opencontainers.image.description='Image of ${{ inputs.repository }}'
          org.opencontainers.image.licenses='Dime Copyright (c) 2022'

    - name: Build & push docker images
      uses: kkp-dfs/dime-github-actions-workflows/kaniko@main
      with:
        image: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
