name: Merge Test PR
description: Merge Pull-Request for testing

inputs:
  repository:
    description: The owner and repository name
    required: true
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: true
  target_ref:
    description: The branch or tag ref or commit SHA that will be merged to base code.
    required: true
  gh_access_token:
    description: GitHub access token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.base_ref }}
  
    - name: Merge no commit and no fast-forward
      shell: bash
      run: |
        cat <<EOF > .netrc
        machine github.com
          login $GH_ACCESS_TOKEN
          password x-oauth-basic
        EOF
        git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git fetch
        git merge --no-commit --no-ff ${{ inputs.target_ref }}
