name: Jenkins Trigger
description: Trigger jenkins job

inputs:
  url:
    description: 'Jenkins full URL including http/https protocol'
    required: true
  user_name: 
    description: 'User name of Jenkins'
    required: true
  api_token:
    description: 'Jenkins API token'
    required: true
  job_name:
    description: 'Job name'
    required: true
  parameter:
    description: 'Job parameter in JSON format. ex) {"param1":"value1"} '
    required: false
  wait:
    description: 'Waiting for job completion or not'
    required: false
    default: "true"
  timeout:
    description: 'Timeout (seconds) for github action. Set 600s as default'
    required: false
    default: "600"
  slack_channel:
    description: The slack channel that send notification.
    required: false
  slack_webhook:
    description: The slack webhook url
    required: true

runs:
  using: composite
  steps:
    - name: Trigger ${{ inputs.job_name }} job
      id: jenkins
      uses: joshlk/jenkins-githubaction@master
      with:
          url: ${{ inputs.url }}
          username: ${{ inputs.user_name }}
          api_token: ${{ inputs.api_token }}
          job_name: ${{ inputs.job_name }}
          parameters: ${{ inputs.parameter }}
          timeout: ${{ inputs.timeout }}
          wait: ${{ inputs.wait }}
  
    - id: success_coverage
      if: ${{ success() }}
      shell: bash
      run: |
        echo "::set-output name=color::#2EB67D"
        echo "::set-output name=title::${{ inputs.job_name }} testing is PASS"

    - id: fail_coverage
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "::set-output name=color::#E01E5A"
        echo "::set-output name=title::${{ inputs.application_name }} testing is FAIL"

    - name: Slack Notification
      if: ${{ always() }}
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "${{ steps.fail_coverage.outputs.title || steps.success_coverage.outputs.title }}",
            "attachments": [
              {
                "color": "${{ steps.fail_coverage.outputs.color || steps.success_coverage.outputs.color }}",
                "blocks": [
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "image",
                        "image_url": "${{ github.event.sender.avatar_url }}",
                        "alt_text": "${{ github.event.sender.login }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.event.sender.login }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Jenkins Job: ${{ steps.jenkins.outputs.build_url }}"
                    },
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repository*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Event*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.event_name }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Ref*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.ref_name }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                      }
                    ]
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook }}