name: Jenkins Trigger
description: Trigger jenkins job

inputs:
  url:
    description: 'Jenkins full URL including http/https protocol'
    required: true
  user_name: 
    description: 'User name of Jenkins'
    required: true
  api_token:
    description: 'Jenkins API token'
    required: true
  job_name:
    description: 'Job name'
    required: true
  parameter:
    description: 'Job parameter in JSON format. ex) {"param1":"value1"} '
    required: false
  wait:
    description: 'Waiting for job completion or not'
    required: false
    default: "true"
  timeout:
    description: 'Timeout (seconds) for github action. Set 600s as default'
    required: false
    default: "600"
  slack_channel:
    description: The slack channel that send notification.
    required: false
  slack_webhook:
    description: The slack webhook url
    required: true

runs:
  using: composite
  steps:
    - name: Trigger ${{ inputs.job_name }} job
      uses: jabbukka/jenkins-trigger@main
      with:
          url: http://jenkins.qa.svc.cluster.local:8080
          user_name: parse-kkp
          api_token: ${{ secrets.jenkins_api_token }}
          job_name: API-E2E
          parameter: '{"BRANCH":"main","ENVIRONMENT":"sit","TAG":"-i SIT"}'
          wait: "true"
          timeout: "1000"