name: Node Setup
description: Install node version and set cache of node modules

inputs:
  node-version:
    description: Version of node that would like to install
    required: true
    default: '16'

runs:
  using: composite
  steps:
    - name: Install node version ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache module and tools
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
          */*/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.repository }}-
