name: Checkout and merge commit action
description: Checkout and merge commit to base branch

inputs:
  repository:
    description: The owner and repository name
    required: false
    default: ${{ github.repository }}
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: false
    default: ${{ github.base_ref || 'main' }}
  target_ref:
    description: The branch or tag ref or commit SHA that will be merged to base code.
    required: false
    default: ${{ github.head_ref || github.ref_name }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.base_ref }}
        clean: true
    - name: Checkout repository
      shell: bash
      run: |
        git clone ${{ inputs.repository }} .
        git checkout ${{ inputs.base_ref }}

    - shell: bash
      if: ${{ inputs.base_ref != inputs.target_ref }}
      run: |
        git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git fetch
        git merge --no-commit --no-ff origin/${{ inputs.target_ref }}
