name: Dime common action
description: Common action of Dime workflow

inputs:
  gh_access_token:
    description: GitHub access token
    required: true

runs:
  using: composite
  steps:
    - name: Create .netrc file
      shell: sh
      run: |
        cat <<EOF > .netrc
        machine github.com
          login ${{ inputs.gh_access_token }}
          password x-oauth-basic
        EOF
        chmod 600 .netrc
        cp .netrc $HOME/.netrc
