name: Build image
description: Build docker image by kaniko

inputs:
  repository:
    description: The owner and repository name
    required: true
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: true
  target_ref:
    description: The branch or tag ref or commit SHA that will be merged to base code.
    required: true
  image_repo:
    description: The image repository
    required: true
  image_tag:
    description: The image tag
    required: true
  gh_access_token:
    description: GitHub access token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout and merge PR to base branch
      uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
      with:
        repository: ${{ inputs.repository }}
        base_ref: ${{ inputs.base_ref }}
        target_ref: ${{ inputs.target_ref }}
        gh_access_token: ${{ inputs.gh_access_token }}
    - name: build image
      uses: docker://gcr.io/kaniko-project/executor:debug
      with:
        args: --dockerfile=Dockerfile --destination=915060398631.dkr.ecr.ap-southeast-1.amazonaws.com/kkp-dfs/ubuntu:latest
