name: Build image
description: Build docker image by kaniko

inputs:
  repository:
    description: The owner and repository name
    required: true
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: true
  target_ref:
    description: The branch or tag ref or commit SHA that will be merged to base code.
    required: true
  image:
    description: Docker image name
    required: true
  build_args:
    description: List of build-time variables
    required: false
  gh_access_token:
    description: GitHub access token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout and merge PR to base branch
      uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
      with:
        repository: ${{ inputs.repository }}
        base_ref: ${{ inputs.base_ref }}
        target_ref: ${{ inputs.target_ref }}
        gh_access_token: ${{ inputs.gh_access_token }}
    - name: ECR login
      run: |
        CREDS=$(aws ecr get-authorization-token --region ap-southeast-1 --registry-id 915060398631 \
        | jq -r '.authorizationData[0].authorizationToken')
        mkdir -p ~/.docker
        cat > ~/.docker/config.json <<EOF
        {"auths":{"915060398631.dkr.ecr.ap-southeast-1.amazonaws.com":{"auth":"$CREDS"}}}
        EOF
    - name: build image
      uses: docker://gcr.io/kaniko-project/executor:debug
      with:
        entrypoint: /busybox/sh
        args: >-
          -c "cp -R ~/.docker /kaniko; 
          /kaniko/executor --dockerfile=Dockerfile --cache --destination=${{ inputs.image }}"
