name: Kaniko
description: Build docker image by kaniko

inputs:
  image:
    description: docker image
    required: true
  build_args:
    description: list of build arguments
    required: false
  labels:
    description: docker image labels
    required: false
outputs:
  image:
    description: docker image
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.image }}
    - ${{ inputs.build_args }}
    - ${{ inputs.labels }}