name: Kaniko
description: Build docker image by kaniko

inputs:
  registry:
    description: docker registry
    required: false
    default: 915060398631.dkr.ecr.ap-southeast-1.amazonaws.com
  token:
    description: registry authentication token
    required: true
  image:
    description: docker image
    required: true
  build_args:
    description: list of build arguments
    required: false
  target:
    description: indicate which build stage is the target build stage.
    required: false
    default: ''
  labels:
    description: docker image labels
    required: false
  dockerfile:
    description: Path to the dockerfile to be built. (default "Dockerfile")
    required: false
    default: Dockerfile
outputs:
  image:
    description: docker image
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.registry }}
    - ${{ inputs.token }}
    - ${{ inputs.image }}
    - ${{ inputs.build_args }}
    - ${{ inputs.labels }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.target }}