name: Dime DAGS Deploy workflows

on:
  workflow_call:
    inputs:
      helm_ref:
        description: commit reference of helm repository
        required: false
        type: string
        default: main
      cluster_prefix:
        description: cluster prefix
        required: false
        type: string
        default: dime
      environment:
        description: Environment that would like to deploy services
        required: false
        default: sit
        type: string
      namespace:
        description: Kubernetes namespace
        required: false
        type: string
        default: etl
      repository:
        description: GitHub Repository
        required: false
        type: string
        default: ${{ github.repository }}
      ref_name:
        description: Git commit's reference name
        required: false
        type: string
        default: ${{ github.ref_name }}
    secrets:
      gh_access_token:
        required: true

jobs:
  dag:
    runs-on: [self-hosted, linux, main, deployment]
    container:
      image: public.ecr.aws/c2u4x1k5/ubuntu:21.04
      volumes:
        - /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
    steps:
      - uses: kkp-dfs/dime-github-actions-workflows/deploy-dags@main
        with:
          environment: ${{ inputs.environment }}
          helm_ref: ${{ inputs.helm_ref }}
          cluster: ${{ inputs.cluster }}
          namespace: ${{ inputs.namespace }}
          repository: ${{ inputs.repository }}
          ref_name: ${{ inputs.ref_name }}
          gh_access_token: ${{ secrets.gh_access_token }}