name: Dime DAGS Deploy workflows

on:
  workflow_call:
    inputs:
      helm_ref:
        description: commit reference of helm repository
        required: false
        type: string
        default: main
    secrets:
      gh_access_token:
        required: true

jobs:
  dag:
    runs-on: [self-hosted, linux, main, deployment]
    steps:
      - uses: kkp-dfs/dime-github-actions-workflows/common@main
        with:
          gh_access_token: ${{ secrets.gh_access_token }}
      - name: Checkout dags repository
        uses: actions/checkout@v2
      - name: Checkout dags_common_lib
        run: git clone https://github.com/kkp-dfs/dags_common_lib.git dags/dags_common_lib
      - run: ls -l dags/
      - run: ls -l dags/dags_common_lib
