name: Dime App Release

on:
  workflow_call:
    inputs:
      target_env:
        description: Target environment of the application
        required: true
        type: string
      repository:
        description: The owner and repository name
        required: false
        type: string
        default: ${{ github.repository }}
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: false
        type: string
        default: ${{ github.base_ref || 'main' }}
      platform:
        description: ios or android or both
        type: string
        required: false
        default: both

    secrets:
      gh_access_token:
        required: true

jobs:
  prepare:
    name: Prepare environment secret file
    runs-on: [self-hosted, linux, main, deployment]
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1
      - name: Checkout code
        uses: kkp-dfs/dime-github-actions-workflows/checkout@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
      - name: Generate environment secret file
        run: |
          JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          echo "{\"role\":\"kubernetes-actions-runner\",\"jwt\":\"$JWT\"}" > payload.json
          TOKEN=$(curl -d @payload.json https://vault.mydime.tech/v1/auth/kubernetes/actions-runner/dime-main/login | jq -r '.auth.client_token')
          DATA=$(curl -H "X-VAULT-TOKEN:$TOKEN" https:/vault.mydime.tech/v1/secrets/data/services/dime-app/${{ inputs.target_env }})

          export DIRECTUS_ACCESS_TOKEN=$(echo $DATA | jq -r ".data.data.DIRECTUS_ACCESS_TOKEN")
          export PASSWORD_HASHING_SALT=$(echo $DATA | jq -r ".data.data.PASSWORD_HASHING_SALT")
          export SECURE_ED25519_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SECURE_ED25519_PUBLIC_KEY")
          export SECURE_RSA_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SECURE_RSA_PUBLIC_KEY")
          export SIGN_IN_RSA_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SIGN_IN_RSA_PUBLIC_KEY")

          curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst
          ./envsubst < environment_secret_template.yaml > environment_secret_${{ inputs.target_env }}.yaml
      - name: Create key properties
        run: |
          JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          echo "{\"role\":\"kubernetes-actions-runner\",\"jwt\":\"$JWT\"}" > payload.json
          TOKEN=$(curl -d @payload.json https://vault.mydime.tech/v1/auth/kubernetes/actions-runner/dime-main/login | jq -r '.auth.client_token')
          DATA=$(curl -H "X-VAULT-TOKEN:$TOKEN" https:/vault.mydime.tech/v1/infrastructure/data/mac-mini-01)

          export KEYSTORE_PASSWORD=$(echo $DATA | jq -r ".data.data.android_release_keystore_password")
          cat <<EOF > key.properties
          keyAlias=release
          keyPassword=${KEYSTORE_PASSWORD}
          storeFile=/Users/dime/.android/release.keystore
          storePassword=${KEYSTORE_PASSWORD}
          EOF
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dime_app_${{ inputs.target_env }}_${{ github.sha }}
          path: |
            environment_secret_${{ inputs.target_env }}.yaml
            key.properties
          retention-days: 1

  get_code:
    name: Get source code and generate config
    runs-on: [self-hosted, macOS]
    needs: [prepare]
    env:
      GITHUB_TOKEN: ${{ secrets.gh_access_token }}
    steps:
      - name: Checkout code
        uses: kkp-dfs/dime-github-actions-workflows/checkout@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
      - name: Common preparation
        uses: kkp-dfs/dime-github-actions-workflows/common@main
        with:
          gh_access_token: ${{ inputs.gh_access_token }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dime_app_${{ inputs.target_env }}_${{ github.sha }}
      - name: Generate config and secret
        run: |
          export PATH=/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/flutter/bin:$PATH
          export RBENV_VERSION=2.7.5
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          source /Users/dime/.bash_profile
          make gen-config-${{ inputs.target_env }}

  build_android:
    name: Build and Distribute Android application
    runs-on: [self-hosted, macOS]
    needs: [get_code]
    if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
    steps:
      - name: Create or copy essential file for build and distribute android application
        run: |
          cat <<EOF > ./android/local.properties
          sdk.dir=/Users/dime/Library/Android/sdk
          flutter.sdk=/opt/flutter
          flutter.buildMode=debug
          flutter.versionName=1.0.0
          flutter.versionCode=1
          EOF

          mv key.properties ./android/
          cp /Users/dime/dime_app_release_files/google-services-${{ inputs.target_env }}.json ./android/app/google-services.json
          cp /Users/dime/dime_app_release_files/service_credentials_${{ inputs.target_env }}.json ./android/app/src/${{ inputs.target_env }}/service_credentials.json
      - name: Build and distribute application
        run: |
          export PATH=/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/flutter/bin:$PATH
          export RBENV_VERSION=2.7.5
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          source /Users/dime/.bash_profile

          cd android
          gradle wrapper
          bundle install
          bundle update fastlane
          bundle exec fastlane -v
          bundle exec fastlane update_plugins
          bundle exec fastlane android_${{ inputs.target_env }}_app

  build_ios:
    name: Build and Distribute IOS application
    runs-on: [self-hosted, macOS]
    needs: [get_code]
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'both'  }}
    steps:
      - name: Build and distribute application
        run: |
          export PATH=/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/flutter/bin:$PATH
          export RBENV_VERSION=2.7.5
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          source /Users/dime/.bash_profile

          cd ios
          bundle install
          bundle update fastlane
          bundle exec fastlane -v
          bundle exec fastlane update_plugins
          bundle exec fastlane ios_${{ inputs.target_env }}_app