name: Dime Golang CI

on:
  workflow_call:
    inputs:
      repository:
        description: The owner and repository name
        required: true
        type: string
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: true
        type: string
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: true
        type: string
    secrets:
      gh_access_token:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            

      - name: Install go modules
        run: |
          make tidy
          make tools-install

  unit-test:
    name: Run unit testing
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            ${{ runner.os }}-go-

      - name: Run test-cases
        run: |
          make unit-test
          make generate-unitcoverage

      - uses: Nef10/lcov-reporter-action@v0.3.0
        with:
          github-token: ${{ github.token }}
          lcov-file: unitcoverage.lcov
          pr_number: ${{ github.event.number }}

  integration-test:
    name: Run integration test
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            ${{ runner.os }}-go-

      - name: Run test-cases
        run: |
          make integration-test
          make generate-intcoverage

      - uses: Nef10/lcov-reporter-action@v0.3.0
        with:
          github-token: ${{ github.token }}
          lcov-file: integrationcoverage.lcov
          pr_number: ${{ github.event.number }}
