name: Dime CI/CD workflow

on:
  workflow_call:
    inputs:
      image:
        description: Docker image name
        required: false
        type: string
        default: ${{ github.repository }}
      current:
        description: The current tag of docker image
        required: false
        type: string
        default: ${{ github.sha }}
      tag:
        description: Tag name that attach to image
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  promote:
    name: Promote docker image's tag
    runs-on: [self-hosted, linux, main]
    steps:
      - uses: kkp-dfs/dime-github-actions-workflows/retagging-image@main