name: Dime Golang CI

on:
  workflow_call:
    inputs:
      repository:
        description: The owner and repository name
        required: true
        type: string
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: true
        type: string
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: true
        type: string
    secrets:
      gh_access_token:
        required: true

jobs:
  setup:
    name: Install dependencies and keep caches
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
    steps:
      - name: Checkout base branch
        uses: kkp-dfs/dime-action-golang-setup@v1
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install go modules
        run: |
          make tidy
          make tools-install

  unit-test:
    name: Run unit testing
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
    steps:
      - name: Checkout base branch
        uses: kkp-dfs/dime-action-golang-setup@v1
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Run test-cases
        run: |
          make unit-test
          make generate-unitcoverage

      - name: Create coverage report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: unitcoverage.lcov
          minimum-coverage: 80
          artifact-name: unittest-coverage-report
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  integration-test:
    name: Run integration test
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
    steps:
      - name: Checkout base branch
        uses: kkp-dfs/dime-action-golang-setup@v1
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Run test-cases
        run: |
          make integration-test
          make generate-intcoverage

      - name: Create coverage report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: integrationcoverage.lcov
          minimum-coverage: 60
          artifact-name: integation-coverage-report
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  build:
    name: Build & push docker images to registry
    needs: [unit-test]
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout and merge PR to base branch
        uses: kkp-dfs/dime-action-merge-test-pr@v1
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.gh_access_token }}

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: https://${{ steps.ecr.outputs.registry }}
          username: AWS
          password: ${{ steps.ecr.outputs.token }}
      
      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.ecr.outputs.repository }}
          tags: |
            type=ref,event=pr,suffix=-latest
            type=ref,event=pr,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
            type=ref,event=branch,pattern=main,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
            type=ref,event=branch,pattern=main,value=latest

      - name: Build & push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
