name: Dime App workflow

on:
  workflow_call:
    inputs:
      application_name:
        description: Name of application
        required: true
        type: string
      repository:
        description: The owner and repository name
        required: false
        type: string
        default: ${{ github.repository }}
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: false
        type: string
        default: ${{ github.base_ref || 'main' }}
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: false
        type: string
        default: ${{ github.head_ref || github.ref_name }}
      minimum_coverage:
        description: "The minimum coverage to pass the check. Optional. Default: `0` (always passes)"
        required: false
        type: number
        default: 80
      slack_channel:
        description: The slack channel that send notification.
        type: string
        required: true

    secrets:
      gh_access_token:
        required: true
      slack_webhook:
        required: true

jobs:
  prepare:
    name: Prepare parameters
    runs-on: [self-hosted, linux, build]
    outputs:
      ecr_username: ${{ steps.paramater.outputs.username }}
      ecr_password: ${{ steps.paramater.outputs.password }}
      matrix: ${{ steps.paramater.outputs.matrix }}
    steps:
      - id: paramater
        run: |
          TOKEN=$(aws ecr get-authorization-token --region ap-southeast-1 --output text \
          --query 'authorizationData[].authorizationToken' | base64 -d)
          echo "::add-mask::$TOKEN"
          echo "::set-output name=username::$(echo $TOKEN | cut -d: -f1)"
          echo "::set-output name=password::$(echo $TOKEN | cut -d: -f2)"
          echo "::set-output name=matrix::$(echo "{\"include\": ${{ secrets.SLACK_CHANNELS }} }")"

  unit-test:
    name: Run unit testing
    needs: prepare
    runs-on: [self-hosted, linux, deployment]
    container:
      image: 915060398631.dkr.ecr.ap-southeast-1.amazonaws.com/flutter:2.8.1-stable
      credentials:
        username: ${{ needs.prepare.outputs.ecr_username }}
        password: ${{ needs.prepare.outputs.ecr_password }}
      volumes:
        - /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
    env:
      SLACK_ICON: https://avatars.githubusercontent.com/u/90231066?s=200&v=4
      SLACK_USERNAME: GitHub Actions
      SLACK_CHANNEL: ${{ inputs.slack_channel }}
      SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
    continue-on-error: true
    steps:
      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            /opt/flutter/.pub-cache
          key: ${{ runner.os }}-flutter-${{ inputs.repository }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ inputs.repository }}-

      - name: Checkout branch
        uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.gh_access_token }}

      - name: Generate environment secret file
        shell: bash
        run: |
          JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          echo "{\"role\":\"kubernetes-actions-runner\",\"jwt\":\"$JWT\"}" > payload.json
          TOKEN=$(curl -d @payload.json https://vault.mydime.tech/v1/auth/kubernetes/actions-runner/main/login | jq -r '.auth.client_token')
          DATA=$(curl -H "X-VAULT-TOKEN:$TOKEN" https:/vault.mydime.tech/v1/secrets/data/services/dime-app/testing)

          export DIRECTUS_ACCESS_TOKEN=$(echo $DATA | jq -r ".data.data.DIRECTUS_ACCESS_TOKEN")
          export PASSWORD_HASHING_SALT=$(echo $DATA | jq -r ".data.data.PASSWORD_HASHING_SALT")
          export SECURE_ED25519_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SECURE_ED25519_PUBLIC_KEY")
          export SECURE_RSA_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SECURE_RSA_PUBLIC_KEY")
          export SIGN_IN_RSA_PUBLIC_KEY=$(echo $DATA | jq -r ".data.data.SIGN_IN_RSA_PUBLIC_KEY")
          export PATH=/opt/flutter/bin:$PATH

          envsubst < environment_secret_template.yaml > environment_secret.yaml
          make gen-config-sit
    
      - name: Run flutter unit-test
        uses: kkp-dfs/dime-github-actions-workflows/flutter-testing@main
        with:
          application_name: ${{ inputs.application_name }}
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          artifact_name: unittest-coverage-report
          gh_access_token: ${{ secrets.gh_access_token }}
          minimum_coverage: 80

      - name: Success Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: This repo passed all test cases of unit-test and there is coverage over than ${{ inputs.minimum_coverage }}%
          SLACK_TITLE: ${{ inputs.application_name }} unit-test is PASS

      - name: Failure Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: This repo fail on some test cases of unit-test or there is coverage less than ${{ inputs.minimum_coverage }}%
          SLACK_TITLE: ${{ inputs.application_name }} unit-test is FAIL
