name: Dime Service Continuous Delivery

on:
  workflow_call:
    inputs:
      environment:
        description: Environment that would like to deploy services
        required: true
        default: sit
        type: string
      release_name:
        description: Release name of service
        required: true
        type: string
      application_name:
        description: Name of application
        required: true
        type: string
      application_endpoints:
        description: Endpoints of application
        required: true
        type: string
      ref:
        description: commit reference of repository
        required: false
        type: string
        default: main
    secrets:
      gh_access_token:
        required: true

jobs:
  argocd:
    name: Apply argo application to kubernetes cluster
    runs-on: [self-hosted, linux, deployment]
    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout Dime helm repository
        uses: actions/checkout@v2
        with:
          repository: kkp-dfs/dime-helm.git
          ref: ${{ inputs.ref }}

      - name: Apply Dime ArgoCD Application Helm
        run: |
          helm template ${{ inputs.release_name }} charts/dime-application \
          -f values/${{ inputs.application_name }}/values.yaml \
          -f values/${{ inputs.application_name }}/values-${{ inputs.environment }}.yaml
          --set "source.username=${{ secrets.gh_access_token }}" \
          --set "source.password=x-oauth-basic" \
          --set "destination.cluster=${{ inputs.environment }}" \
          --set "application.values.virtualService.hosts={ ${{ inputs.application_endpoints }} }" \