name: Dime NodeJS Continuous Integration

on:
  workflow_call:
    inputs:
      repository:
        description: The owner and repository name
        required: true
        type: string
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: true
        type: string
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: true
        type: string

    secrets:
      gh_access_token:
        required: true

    outputs:
      docker_image:
        description: Docker image metadata
        value: ${{ jobs.build.outputs.docker_image }}

jobs:
  setup:
    name: Install dependencies and keep caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and merge PR to base branch
        uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.gh_access_token }}

      - name: Set up go version and caches
        uses: kkp-dfs/dime-github-actions-workflows/node-setup@main

      - name: Install node modules
        run: npm install

  lint:
    name: Run lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and merge PR to base branch
        uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.gh_access_token }}

      - name: Set up go version and caches
        uses: kkp-dfs/dime-github-actions-workflows/node-setup@main

      - name: Run lint
        run: npm run lint

  build:
    name: Build & push docker images to registry
    needs: [lint]
    runs-on: [self-hosted, linux]
    outputs:
      docker_image: ${{ steps.build.outputs.docker_image }}
    steps:
      - name: Checkout and merge PR to base branch
        uses: kkp-dfs/dime-github-actions-workflows/merge-test-pr@main
        with:
          repository: ${{ inputs.repository }}
          base_ref: ${{ inputs.base_ref }}
          target_ref: ${{ inputs.target_ref }}
          gh_access_token: ${{ secrets.gh_access_token }}

      - name: Build and push docker image
        id: build
        uses: kkp-dfs/dime-github-actions-workflows/docker-build-push@main
        with:
          repository: ${{ inputs.repository }}