name: Dime Golang CI

on:
  workflow_call:
    inputs:
      repository:
        description: The owner and repository name
        required: true
        type: string
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: true
        type: string
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: true
        type: string
    secrets:
      gh_access_token:
        required: true

jobs:
  setup:
    name: Install dependencies and keep caches
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          cat <<EOF > .netrc
          machine github.com
            login $GH_ACCESS_TOKEN
            password x-oauth-basic
          EOF
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
            ./.netrc
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            

      - name: Install go modules
        run: |
          make tidy
          make tools-install

  unit-test:
    name: Run unit testing
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
            ./.netrc
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            ${{ runner.os }}-go-

      - name: Run test-cases
        run: |
          make unit-test
          make generate-unitcoverage

      - name: Create coverage report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: unitcoverage.lcov
          minimum-coverage: 80
          artifact-name: unittest-coverage-report
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  integration-test:
    name: Run integration test
    needs: setup
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/kkp-dfs/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Merge no commit and no fast-forward
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
            ./.netrc
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            ${{ runner.os }}-go-

      - name: Run test-cases
        run: |
          make integration-test
          make generate-intcoverage

      - name: Create coverage report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: integrationcoverage.lcov
          minimum-coverage: 60
          artifact-name: integation-coverage-report
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  build:
    name: Build & push docker images to registry
    needs: [unit-test]
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.base_ref }}

      - name: Merge no commit and no fast-forward
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch
          git merge --no-commit --no-ff ${{ inputs.target_ref }}

      - name: Cache module and tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ./vendor
            ./.netrc
          key: ${{ runner.os }}-go-${{ inputs.repository }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ inputs.repository }}-
            ${{ runner.os }}-go-

      - name: Get ECR details
        id: ecr
        run: |
          REPOSITORY=$(aws ecr describe-repositories --region ap-southeast-1 --output text \
          --query 'repositories[].repositoryUri' --repository-name '${{ inputs.repository }}')
          TOKEN=$(aws ecr get-authorization-token --region ap-southeast-1 --output text \
          --query 'authorizationData[].authorizationToken' | base64 -d | cut -d: -f2)

          echo "::add-mark::$TOKEN"
          echo "::set-output name=token::$TOKEN"
          echo "::set-output name=registry::$(echo $REPOSITORY | sed 's|${{ inputs.repository }}||')"
          echo "::set-output name=repository::$REPOSITORY"

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: https://${{ steps.ecr.outputs.registry }}
          username: AWS
          password: ${{ steps.ecr.outputs.token }}
      
      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.ecr.outputs.repository }}
          tags: |
            type=ref,event=pr,suffix=-latest
            type=ref,event=pr,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
            type=ref,event=branch,pattern=main,suffix=-{{ date 'YYYYMMDD-HHmmss' }}
            type=ref,event=branch,pattern=main,value=latest

      - name: Build & push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
